# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'BuildUI.ui'
##
## Created by: Qt User Interface Compiler version 6.11.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QAbstractButton, QApplication, QDialog, QDialogButtonBox,
    QGroupBox, QLabel, QSizePolicy, QTabWidget,
    QWidget)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        if not Dialog.objectName():
            Dialog.setObjectName(u"Dialog")
        Dialog.resize(1221, 752)
        self.buttonBox = QDialogButtonBox(Dialog)
        self.buttonBox.setObjectName(u"buttonBox")
        self.buttonBox.setGeometry(QRect(290, 710, 341, 32))
        self.buttonBox.setOrientation(Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QDialogButtonBox.StandardButton.Cancel|QDialogButtonBox.StandardButton.Ok)
        self.main_tabWidget = QTabWidget(Dialog)
        self.main_tabWidget.setObjectName(u"main_tabWidget")
        self.main_tabWidget.setGeometry(QRect(20, 30, 1191, 671))
        self.main_tabWidget.setAutoFillBackground(False)
        self.tab = QWidget()
        self.tab.setObjectName(u"tab")
        self.player2_groupBox = QGroupBox(self.tab)
        self.player2_groupBox.setObjectName(u"player2_groupBox")
        self.player2_groupBox.setGeometry(QRect(90, 40, 150, 120))
        self.label_p2 = QLabel(self.player2_groupBox)
        self.label_p2.setObjectName(u"label_p2")
        self.label_p2.setGeometry(QRect(10, 30, 60, 80))
        self.label_p2.setPixmap(QPixmap(u"../Images/Playing Cards/Playing Cards/SVG-cards-1.3/2_of_clubs.svg"))
        self.label_p2.setScaledContents(True)
        self.player1_groupBox = QGroupBox(self.tab)
        self.player1_groupBox.setObjectName(u"player1_groupBox")
        self.player1_groupBox.setGeometry(QRect(20, 210, 150, 120))
        self.label_p1 = QLabel(self.player1_groupBox)
        self.label_p1.setObjectName(u"label_p1")
        self.label_p1.setGeometry(QRect(10, 30, 60, 80))
        self.label_p1.setPixmap(QPixmap(u"../Images/Playing Cards/Playing Cards/SVG-cards-1.3/2_of_clubs.svg"))
        self.label_p1.setScaledContents(True)
        self.player3_groupBox = QGroupBox(self.tab)
        self.player3_groupBox.setObjectName(u"player3_groupBox")
        self.player3_groupBox.setGeometry(QRect(380, 0, 150, 120))
        self.label_p3 = QLabel(self.player3_groupBox)
        self.label_p3.setObjectName(u"label_p3")
        self.label_p3.setGeometry(QRect(10, 30, 60, 80))
        self.label_p3.setPixmap(QPixmap(u"../Images/Playing Cards/Playing Cards/SVG-cards-1.3/2_of_clubs.svg"))
        self.label_p3.setScaledContents(True)
        self.player4_groupBox = QGroupBox(self.tab)
        self.player4_groupBox.setObjectName(u"player4_groupBox")
        self.player4_groupBox.setGeometry(QRect(650, 0, 150, 120))
        self.label_p4 = QLabel(self.player4_groupBox)
        self.label_p4.setObjectName(u"label_p4")
        self.label_p4.setGeometry(QRect(10, 20, 60, 80))
        self.label_p4.setPixmap(QPixmap(u"../Images/Playing Cards/Playing Cards/SVG-cards-1.3/2_of_clubs.svg"))
        self.label_p4.setScaledContents(True)
        self.label = QLabel(self.tab)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(-10, 0, 1191, 641))
        self.label.setPixmap(QPixmap(u"images/table.png"))
        self.label.setScaledContents(True)
        self.player5_groupBox = QGroupBox(self.tab)
        self.player5_groupBox.setObjectName(u"player5_groupBox")
        self.player5_groupBox.setGeometry(QRect(910, 50, 150, 120))
        self.label_p5 = QLabel(self.player5_groupBox)
        self.label_p5.setObjectName(u"label_p5")
        self.label_p5.setGeometry(QRect(10, 20, 60, 80))
        self.label_p5.setPixmap(QPixmap(u"../Images/Playing Cards/Playing Cards/SVG-cards-1.3/2_of_clubs.svg"))
        self.label_p5.setScaledContents(True)
        self.player6_groupBox = QGroupBox(self.tab)
        self.player6_groupBox.setObjectName(u"player6_groupBox")
        self.player6_groupBox.setGeometry(QRect(1000, 230, 150, 120))
        self.label_p6 = QLabel(self.player6_groupBox)
        self.label_p6.setObjectName(u"label_p6")
        self.label_p6.setGeometry(QRect(10, 20, 60, 80))
        self.label_p6.setPixmap(QPixmap(u"../Images/Playing Cards/Playing Cards/SVG-cards-1.3/2_of_clubs.svg"))
        self.label_p6.setScaledContents(True)
        self.player7_groupBox = QGroupBox(self.tab)
        self.player7_groupBox.setObjectName(u"player7_groupBox")
        self.player7_groupBox.setGeometry(QRect(920, 440, 150, 120))
        self.label_p7 = QLabel(self.player7_groupBox)
        self.label_p7.setObjectName(u"label_p7")
        self.label_p7.setGeometry(QRect(10, 20, 60, 80))
        self.label_p7.setPixmap(QPixmap(u"../Images/Playing Cards/Playing Cards/SVG-cards-1.3/2_of_clubs.svg"))
        self.label_p7.setScaledContents(True)
        self.player8_groupBox = QGroupBox(self.tab)
        self.player8_groupBox.setObjectName(u"player8_groupBox")
        self.player8_groupBox.setGeometry(QRect(630, 480, 150, 120))
        self.label_p8 = QLabel(self.player8_groupBox)
        self.label_p8.setObjectName(u"label_p8")
        self.label_p8.setGeometry(QRect(10, 20, 60, 80))
        self.label_p8.setPixmap(QPixmap(u"../Images/Playing Cards/Playing Cards/SVG-cards-1.3/2_of_clubs.svg"))
        self.label_p8.setScaledContents(True)
        self.player9_groupBox = QGroupBox(self.tab)
        self.player9_groupBox.setObjectName(u"player9_groupBox")
        self.player9_groupBox.setGeometry(QRect(340, 480, 150, 120))
        self.label_p9 = QLabel(self.player9_groupBox)
        self.label_p9.setObjectName(u"label_p9")
        self.label_p9.setGeometry(QRect(10, 20, 60, 80))
        self.label_p9.setPixmap(QPixmap(u"../Images/Playing Cards/Playing Cards/SVG-cards-1.3/2_of_clubs.svg"))
        self.label_p9.setScaledContents(True)
        icon = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.AddressBookNew))
        self.main_tabWidget.addTab(self.tab, icon, "")
        self.label.raise_()
        self.player2_groupBox.raise_()
        self.player1_groupBox.raise_()
        self.player3_groupBox.raise_()
        self.player4_groupBox.raise_()
        self.player5_groupBox.raise_()
        self.player6_groupBox.raise_()
        self.player7_groupBox.raise_()
        self.player8_groupBox.raise_()
        self.player9_groupBox.raise_()
        self.tab_2 = QWidget()
        self.tab_2.setObjectName(u"tab_2")
        self.main_tabWidget.addTab(self.tab_2, "")

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)

        self.main_tabWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(Dialog)
    # setupUi

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QCoreApplication.translate("Dialog", u"Dialog", None))
        self.player2_groupBox.setTitle(QCoreApplication.translate("Dialog", u"Player 2", None))
        self.label_p2.setText("")
        self.player1_groupBox.setTitle(QCoreApplication.translate("Dialog", u"Player 1", None))
        self.label_p1.setText("")
        self.player3_groupBox.setTitle(QCoreApplication.translate("Dialog", u"Player 3", None))
        self.label_p3.setText("")
        self.player4_groupBox.setTitle(QCoreApplication.translate("Dialog", u"Player 4", None))
        self.label_p4.setText("")
        self.label.setText("")
        self.player5_groupBox.setTitle(QCoreApplication.translate("Dialog", u"Player 5", None))
        self.label_p5.setText("")
        self.player6_groupBox.setTitle(QCoreApplication.translate("Dialog", u"Player 6", None))
        self.label_p6.setText("")
        self.player7_groupBox.setTitle(QCoreApplication.translate("Dialog", u"Player 7", None))
        self.label_p7.setText("")
        self.player8_groupBox.setTitle(QCoreApplication.translate("Dialog", u"Player 8", None))
        self.label_p8.setText("")
        self.player9_groupBox.setTitle(QCoreApplication.translate("Dialog", u"Player 9", None))
        self.label_p9.setText("")
        self.main_tabWidget.setTabText(self.main_tabWidget.indexOf(self.tab), QCoreApplication.translate("Dialog", u"Players Hands", None))
        self.main_tabWidget.setTabText(self.main_tabWidget.indexOf(self.tab_2), QCoreApplication.translate("Dialog", u"Settings", None))
    # retranslateUi

